version: '3'

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: ./dockerConf/Dockerfile
    image: virus_mvp_app
    ports:
      - "8050:8050"
    volumes:
      - ./reference_data:/app/reference_data
      - ./reference_surveillance_reports:/app/reference_surveillance_reports
      - ./user_data:/app/user_data
      - ./user_surveillance_reports:/app/user_surveillance_reports
