[workspace]
channels = ["conda-forge", "bioconda"]
# Bioconda supports only Linux (64-bit and AArch64) and macOS (x86_64 and ARM64)
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
# Nextflow is a Bioconda package
# VIRUS-MVP requires Nextflow syntax parser v1 (legacy)
nextflow = "==25.10.4"
# pkg_resources is required (use older version of setuptools)
setuptools = "==81.0.0"
ca-certificates = ">=2026.5.20,<2027"

[pypi-dependencies]
dash = "==1.20.0"
plotly = "==5.24.1"
numpy = "==1.26.4"
dash-bootstrap-components = "==0.11.3"
flask-caching = "==1.10.1"
gunicorn = "==20.1.0"
werkzeug = "==2.0.2"
