version: '3'

volumes:
    letsencrypt:

services:
  app:
    build:
      context: .
      dockerfile: ./dockerConf/app/Dockerfile
    image: covid_mvp_production_app
    ports:
      - "8050:8050"
  nginx:
      build:
        context: .
        dockerfile: ./dockerConf/nginx/Dockerfile
      image: covid_mvp_production_nginx
      ports:
        - 80:80/tcp
        - 443:443/tcp
      environment:
        CERTBOT_EMAIL: owner@company.com
      volumes:
          - letsencrypt:/etc/letsencrypt